nwodb: nwodb nwodb.c interface.c sql_command_processor.c vm.c cursor.c table.c pager.c node.c row.c
	cc -g -o nwodb nwodb.c interface.c sql_command_processor.c vm.c cursor.c table.c pager.c node.c row.c -I.
	
